import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossOrigin="anonymous"></link>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="m-3 p-2">
                  <div className="row border ">
          <Link className="col-4  p-1 border" href="/">
            home
          </Link>
          <Link className="col-4 p-1 border" href="/contact"> 
            Contact
          </Link>
          <Link className="col-4  p-1 border" href="/about">
            about
          </Link>
        </div>
        <div className="row border">
          <div className="col-4 p-1 border h-">sidebar</div>
          <div className="col-8 p-5 border h-75">{children}</div>
        </div>
                <div className="row border">
          <div className="col-12 p-1 border h-75">footer</div>

        </div>
        </div>

      </body>
    </html>
  );
}
